using SCPU.Architecture;
using SCPU.Assembler;
using SCPU.Assembler.Model;
using SCPU.Simulator.Core;

namespace SCPU.Simulator.Debugger;

/// <summary>Supported input program formats.</summary>
public enum ProgramFileType { Binary, Assembly, SCode }
/// <summary>Current debugger execution state.</summary>
public enum SimulatorState { Ready, Running, Paused, Halted, Breakpoint, Faulted }
/// <summary>Reason why an execution operation stopped.</summary>
public enum StopReason { Completed, Paused, Halt, Breakpoint, Address, TickLimit, Cancelled, Faulted }

/// <summary>Result returned by a synchronous execution operation.</summary>
public readonly record struct ExecutionResult(StopReason Reason, long Ticks, ushort ProgramCounter);

/// <summary>Location and content of one source line.</summary>
public sealed record SourceLocation(string Identifier, int Line, string Content);

/// <summary>One word in the logical S-CPU stack.</summary>
public sealed record StackEntry(uint Address, ushort Value, bool IsFramePointer);

/// <summary>Logical stack state derived from SP, FP and the reserved stack region.</summary>
public sealed record StackSnapshot(uint StackPointer, uint? FramePointer, bool IsInitialized,
    IReadOnlyList<StackEntry> Entries);

/// <summary>Annotated word in the loaded ROM image.</summary>
public sealed record RomEntry(
    ushort Address,
    ushort Value,
    string Instruction,
    string Label,
    SourceLocation? Source)
{
    /// <summary>True when this word is a data directive value, not an executable instruction.</summary>
    public bool IsData { get; init; }
}

/// <summary>Immutable processor state published to debugger frontends.</summary>
public sealed record CpuSnapshot(
    ushort Accumulator,
    ushort InstructionRegister,
    ushort ProgramCounter,
    bool Carry,
    bool Indirected,
    Step Step,
    Instruction Instruction,
    AddressingMode AddressingMode,
    ushort Operand,
    ushort DataBus,
    ushort AluOperand,
    ushort NextInstruction,
    string DataSource,
    long Cycles,
    long Instructions,
    SimulatorState State,
    double ActualFrequency,
    double ActualInstructionsPerSecond,
    TimeSpan ExecutionTime,
    StopReason? StopReason,
    string? Fault);

/// <summary>Loaded ROM plus symbols, source mappings and HALT addresses.</summary>
public sealed record ProgramImage(
    FileInfo File,
    ProgramFileType Type,
    byte[] Binary,
    IReadOnlyList<RomEntry> Rom,
    IReadOnlyDictionary<string, uint> Symbols,
    IReadOnlySet<ushort> HaltAddresses)
{
    /// <summary>Gets the complete assembler artifact when the input was assembly or S-Code.</summary>
    public AssemblyResult? AssemblyArtifact { get; init; }
    /// <summary>Gets the original ASM or S-Code text when a source file was loaded.</summary>
    public string? OriginalSourceText { get; init; }
    /// <summary>Gets the assembly generated by the S-Code compiler, when applicable.</summary>
    public string? GeneratedAssemblyText { get; init; }
    /// <summary>Gets the generated assembly document identifier used by source mappings.</summary>
    public string? GeneratedAssemblyIdentifier { get; init; }
    /// <summary>Gets source documents that contribute mapped words to the program.</summary>
    public IReadOnlyDictionary<string, string> SourceDocuments { get; init; } =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
}

/// <summary>Formats encoded S-CPU instructions for debugger frontends.</summary>
public static class InstructionFormatter
{
    /// <summary>Formats operands using compact ROM, RAM and MMIO notation.</summary>
    public static string Format(ushort word)
        => Format(word, useVirtualAddresses: false);

    /// <summary>Formats operands using virtual addresses from the S-CPU memory map.</summary>
    public static string FormatWithVirtualAddresses(ushort word)
        => Format(word, useVirtualAddresses: true);

    private static string Format(ushort word, bool useVirtualAddresses)
    {
        var instruction = (Instruction)(word >> 14);
        var mode = InstructionUtils.GetAddressingMode(word);
        var operand = mode == AddressingMode.ROM ? word & 0x1FFF : word & 0x07FF;
        var value = mode switch
        {
            AddressingMode.Immediate => $"#0x{operand:X3}",
            AddressingMode.RAM when useVirtualAddresses => $"0x{MemoryMap.Ram.Start + operand:X5}",
            AddressingMode.MMIO when useVirtualAddresses => $"0x{MemoryMap.Mmio.Start + operand:X5}",
            AddressingMode.Indirect when useVirtualAddresses => $"@0x{MemoryMap.Ram.Start + operand:X5}",
            AddressingMode.RAM => $"RAM[0x{operand:X3}]",
            AddressingMode.MMIO => $"IO[0x{operand:X3}]",
            AddressingMode.Indirect => $"@RAM[0x{operand:X3}]",
            _ => $"0x{operand:X4}"
        };
        return $"{instruction.ToMnemonic().ToUpperInvariant()} {value}";
    }

    public static SourceLocation? GetSource(object source) => source switch
    {
        Line line => new SourceLocation(line.Source.Source.Identifier, line.Source.Line, line.Source.RawContent),
        _ => null
    };

    /// <summary>Returns true when the source object is a data directive line or an injected constant, not an executable instruction.</summary>
    public static bool IsDataWord(object? source) =>
        source is string || (source is Line line && line.Type == LineType.DataDirective);

    /// <summary>
    /// Formats a data word for display in debugger instruction columns.
    /// Prefers ASCII representation for printable characters, decimal for small values, hex otherwise.
    /// </summary>
    public static string FormatDataInstruction(ushort word)
    {
        if (word is >= 0x0020 and <= 0x007E)
            return $"#d \"{(char)word}\"";
        return $"#d {word}";
    }
}
