namespace SCode.Compiler.CLI
{
    /// <summary>
    /// Supported output formats for the compiler.
    /// </summary>
    public enum OutputFormat
    {
        /// <summary>
        /// Annotated format (human-readable, useful for debugging).
        /// </summary>
        Annotated = SCPU.Assembler.Exporters.OutputFormat.Annotated,

        /// <summary>
        /// Raw binary format.
        /// </summary>
        Binary = SCPU.Assembler.Exporters.OutputFormat.Binary,

        /// <summary>
        /// Intel HEX format.
        /// </summary>
        IntelHex = SCPU.Assembler.Exporters.OutputFormat.IntelHex,

        /// <summary>
        /// Logisim-16 hex format.
        /// </summary>
        Logisim16 = SCPU.Assembler.Exporters.OutputFormat.Logisim16,

        /// <summary>
        /// Verilog memory initialization file.
        /// </summary>
        Verilog = SCPU.Assembler.Exporters.OutputFormat.Verilog,

        /// <summary>
        /// Gowin FPGA memory initialization file.
        /// </summary>
        Gowin = SCPU.Assembler.Exporters.OutputFormat.Gowin,

        /// <summary>
        /// Plain-text symbol table (label-to-address) output.
        /// </summary>
        Symbol = SCPU.Assembler.Exporters.OutputFormat.Symbol,

        /// <summary>
        /// Plain-text assembly source generated by the compiler
        /// without passing through the assembler. 
        /// Useful for inspecting the intermediate ASM.
        /// </summary>
        Assembly
    }
}
