; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps= https://github.com/RobTillaart/MCP23S17
          https://github.com/tzapu/WiFiManager.git
          ESP32Async/ESPAsyncWebServer @ ^3.12.0
          ArduinoJson
          Wire

[env:test_lolin32]
board = lolin32
build_flags = 
  -DDEBUG_SERIAL
  -DMDNS_NAME=\"slinkdev\"
  -DBOARD_ID=ESP32_LOLIN32

[env:dev_esp32_s3]
board = esp32-s3-devkitm-1
build_flags = 
  -DDEBUG_SERIAL
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DMDNS_NAME=\"slinkdev\"
  -DBOARD_ID=ESP32_S3

[env:dev_esp32_c3]
board = esp32-c3-devkitc-02
build_flags = 
  -DDEBUG_SERIAL
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DMDNS_NAME=\"slinkdev\"
  -DBOARD_ID=ESP32_C3

[env:prod_esp32_c3]
board = esp32-c3-devkitc-02
build_flags = 
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_WARN
  -DMDNS_NAME=\"slink\"
  -DBOARD_ID=ESP32_C3
