//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SCodeParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SCodeParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISCodeParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SCodeParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.customTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomTypeName([NotNull] SCodeParser.CustomTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerType([NotNull] SCodeParser.IntegerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseType([NotNull] SCodeParser.BaseTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SCodeParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SCodeParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledStatement([NotNull] SCodeParser.LabeledStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] SCodeParser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.includeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncludeDeclaration([NotNull] SCodeParser.IncludeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.assemblyConstantDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssemblyConstantDeclaration([NotNull] SCodeParser.AssemblyConstantDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] SCodeParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarators([NotNull] SCodeParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarator([NotNull] SCodeParser.VariableDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.arraySpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraySpecifier([NotNull] SCodeParser.ArraySpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializer([NotNull] SCodeParser.VariableInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitializer([NotNull] SCodeParser.ArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.structInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructInitializer([NotNull] SCodeParser.StructInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.structMembersInitializers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructMembersInitializers([NotNull] SCodeParser.StructMembersInitializersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.structMemberInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructMemberInitializer([NotNull] SCodeParser.StructMemberInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] SCodeParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.functionSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSignature([NotNull] SCodeParser.FunctionSignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] SCodeParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] SCodeParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] SCodeParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclaration([NotNull] SCodeParser.StructDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructBody([NotNull] SCodeParser.StructBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.structMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructMemberDeclaration([NotNull] SCodeParser.StructMemberDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.embeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmbeddedStatement([NotNull] SCodeParser.EmbeddedStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>emptyStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement([NotNull] SCodeParser.EmptyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expressionStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] SCodeParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ifStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] SCodeParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>switchStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] SCodeParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>whileStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] SCodeParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>doStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoStatement([NotNull] SCodeParser.DoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] SCodeParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>breakStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] SCodeParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continueStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] SCodeParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>gotoStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoStatement([NotNull] SCodeParser.GotoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>returnStatement</c>
	/// labeled alternative in <see cref="SCodeParser.simpleEmbeddedStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] SCodeParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.ifBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBody([NotNull] SCodeParser.IfBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.forInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInitializer([NotNull] SCodeParser.ForInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.forIterator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForIterator([NotNull] SCodeParser.ForIteratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.switchSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchSection([NotNull] SCodeParser.SwitchSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchLabel([NotNull] SCodeParser.SwitchLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SCodeParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.nonAssignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonAssignmentExpression([NotNull] SCodeParser.NonAssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] SCodeParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] SCodeParser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] SCodeParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpression([NotNull] SCodeParser.CastExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] SCodeParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccess([NotNull] SCodeParser.MemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.methodInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodInvocation([NotNull] SCodeParser.MethodInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] SCodeParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.arrayAccessExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccessExpression([NotNull] SCodeParser.ArrayAccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalExpression</c>
	/// labeled alternative in <see cref="SCodeParser.primaryExpressionStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpression([NotNull] SCodeParser.LiteralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="SCodeParser.primaryExpressionStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierExpression([NotNull] SCodeParser.IdentifierExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenthesisExpressions</c>
	/// labeled alternative in <see cref="SCodeParser.primaryExpressionStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpressions([NotNull] SCodeParser.ParenthesisExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sizeofExpression</c>
	/// labeled alternative in <see cref="SCodeParser.primaryExpressionStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSizeofExpression([NotNull] SCodeParser.SizeofExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] SCodeParser.ConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.orConditionalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrConditionalOrExpression([NotNull] SCodeParser.OrConditionalOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.andConditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndConditionalExpression([NotNull] SCodeParser.AndConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.orBitwiseExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrBitwiseExpression([NotNull] SCodeParser.OrBitwiseExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.xorBitwiseExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXorBitwiseExpression([NotNull] SCodeParser.XorBitwiseExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.andBitwiseExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndBitwiseExpression([NotNull] SCodeParser.AndBitwiseExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] SCodeParser.EqualityExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] SCodeParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpression([NotNull] SCodeParser.ShiftExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] SCodeParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] SCodeParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] SCodeParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementList([NotNull] SCodeParser.StatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] SCodeParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.literalBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralBoolean([NotNull] SCodeParser.LiteralBooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SCodeParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] SCodeParser.IdentifierContext context);
}
