<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="Terminal.Gui" Version="2.0.0-v2-develop.2329" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Compiler\SCode.Compiler.Core\SCode.Compiler.Core.csproj" />
    <ProjectReference Include="..\SCPU.Simulator.Core\SCPU.Simulator.Core.csproj" />
  </ItemGroup>

</Project>
